apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-hive
  labels:
    app: devops-hive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-hive
  template:
    metadata:
      labels:
        app: devops-hive
    spec:
      automountServiceAccountToken: false
      containers:
        - name: devops-hive
          image: docker.io/mahmoudabdelgowad/devops_hive:10
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: Unconfined
          resources:
            limits:
              memory: 1500Mi
              cpu: "500m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /readyz
              port: 80
              httpHeaders:
              - name: Custom-Header
                value: "HTTP = 200"
            initialDelaySeconds: 3
            periodSeconds: 3
