apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-hive-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mabdelgowa/DevOps_Hive.git
    targetRevision: HEAD
    path: k8s/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argoproj
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
