apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      automountServiceAccountToken: false
      containers:
      - name: myapp
        image: docker.io/mahmoudabdelgowad/devops_hive:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 100Mi
