apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.Name }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: {{ .Values.Name }}
        image: {{ .Values.appImage }}
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: Unconfined
        resources:
          limits:
            memory: 1500Mi
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.containerPort }}

