apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-hive
  labels:
    app: devops-hive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-hive
  template:
    metadata:
      labels:
        app: devops-hive
    spec:
      automountServiceAccountToken: false
      containers:
        - name: devops-hive
          image: docker.io/mahmoudabdelgowad/devops_hive:latest
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "1500Mi"
              cpu: "500m"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
            appArmorProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 80
