apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        appArmorProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.appName }}
          image: docker.io/mahmoudabdelgowad/devops_hive:latest
          resources:
            requests:
              memory: {{ .Values.memoryreq }}
              cpu: {{ .Values.cpureq }}
            limits:
              memory: {{ .Values.memorylim }}
              cpu: {{ .Values.cpulim }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
                #            appArmorProfile:
                #              type: RuntimeDefault
          ports:
            - containerPort: 80
