apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopshive-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /temperature
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 8080
          - pathType: Prefix
            path: /metrics
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 8080
          - pathType: Prefix
            path: /version
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: 8080
