# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Python application

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
    
      run: |
        python -m pip install --upgrade pip
        pip install prometheus-client flake8 pytest fastapi uvicorn pytest requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      if: contains(github.event.head_commit.message, 'build')
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest prometheus-client fastapi requests httpx
    - name: Test with pytest
      run: |
        pytest ./test/unit.py
  build_image:
    needs: test
    runs-on: ubuntu-latest

    steps:
    -
        name: Set up QEMU
        if: contains(github.event.head_commit.message, 'build')
        uses: docker/setup-qemu-action@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        if: contains(github.event.head_commit.message, 'build')
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mahmoudabdelgowad/devops_hive:latest  
    -
        name: Build and push for pull requests 
        if: contains(github.event.head_commit.message, 'build')
        uses: docker/build-push-action@v6
        with:
          pull_request: true
          tags: mahmoudabdelgowad/devops_hive:staging  
