name: terrascan

on:
  push:
    branches: [ "enhancement" ] 
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v1'
        policy_type: 'k8s'
        only_warn: true
        non_recursive: false
        sarif_upload: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
          #   category: terrascan
  
    - name: Convert json file into yaml
      uses: mikefarah/yq@master
      with:
        cmd: yq -p json -o yaml terrascan.sarif >  terrascan.yml
    - name: Handling terrascan report
      run: |
            cat terrascan.yml | grep "severity: LOW" -B 5 > terrascan_LOW.yml
            cat terrascan.yml | grep "severity: MEDIUM" -B 5 > terrascan_MEDIUM.yml 
            cat terrascan.yml | grep "severity: HIGH" -B 5 > terrascan_HIGH.yml 
            cat terrascan.yml | grep  "level: note" -B 2 -A 12 > terrascan_note.yml
            cat terrascan.yml | grep  "level: warning" -B 2 -A 12 > terrascan_warning.yml
            cat terrascan.yml | grep  "level: critical" -B 2 -A 12 > terrascan_warning.yml
      continue-on-error: true
    - name: Send mail
      uses: dawidd6/action-send-mail@v4
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, default 25:
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional (recommended) mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Github Actions job result
        # Required recipients' addresses:
        to: mabdelgowad144@gmail.com 
        # Required sender full name (address can be skipped):
        from: Mahmoud # <user@example.com>
        # Optional plain body:
        body: Build job of ${{github.repository}} completed successfully!
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: |
                      terrascan_MEDIUM.yml
                      terrascan_LOW.yml
                      terrascan_HIGH.yml
                      terrascan_note.yml
                      terrascan_warning.yml
                      terrascan_critical.yml
        # Optional priority: 'high', 'normal' (default) or 'low'
        priority: low
